# Generated by Django 4.0.1 on 2022-02-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adabookclubapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AddField(
            model_name='message',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
