# Generated by Django 4.0.1 on 2022-02-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adabookclubapp', '0002_delete_book_message_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='book_author',
            field=models.CharField(default='Jane Doe', max_length=100),
        ),
        migrations.AddField(
            model_name='group',
            name='book_title',
            field=models.CharField(default='A Book', max_length=100),
        ),
    ]
