# Generated by Django 4.0.1 on 2022-02-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adabookclubapp', '0003_group_book_author_group_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='book_pages',
            field=models.IntegerField(default=1),
        ),
    ]
