# Generated by Django 4.0.1 on 2022-02-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adabookclubapp', '0005_remove_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default='ada@adadev.com', max_length=300),
        ),
    ]
