# Generated by Django 4.0.1 on 2022-02-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adabookclubapp', '0006_member_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(default='ada@ada.com', max_length=300),
        ),
    ]
