# Generated by Django 4.0.1 on 2022-01-31 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adabookclubapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookdiscussions',
            old_name='discussion',
            new_name='discussion_id',
        ),
    ]
