# Generated by Django 4.0.1 on 2022-01-31 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adabookclubapp', '0002_rename_discussion_bookdiscussions_discussion_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookDiscussions',
            new_name='BookDiscussion',
        ),
        migrations.RenameModel(
            old_name='MemberGroups',
            new_name='MemberGroup',
        ),
    ]
