# Generated by Django 4.0.1 on 2022-02-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adabookclubapp', '0003_rename_bookdiscussions_bookdiscussion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='groups',
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='groups', to='adabookclubapp.Member'),
        ),
        migrations.DeleteModel(
            name='MemberGroup',
        ),
    ]
