# Generated by Django 4.0.1 on 2022-02-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adabookclubapp', '0004_remove_member_groups_alter_group_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='title',
            field=models.CharField(default='Discussion', max_length=30),
        ),
    ]
