# Generated by Django 4.0.1 on 2022-02-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adabookclubapp', '0006_rename_title_discussion_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='subject',
            field=models.CharField(default='Discussion', help_text='Enter a subject for discussion', max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(help_text='Enter a group name', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(help_text='Enter a username', max_length=30),
        ),
    ]
