# Generated by Django 4.0.1 on 2022-02-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adabookclubapp', '0008_alter_group_group_name_alter_member_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
