# Generated by Django 4.0.1 on 2022-02-03 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adabookclubapp', '0009_discussion_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='book_id',
        ),
    ]
