# Generated by Django 4.0.1 on 2022-02-03 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adabookclubapp', '0010_remove_discussion_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='book_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adabookclubapp.book'),
        ),
    ]
