# Generated by Django 4.0.1 on 2022-02-03 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adabookclubapp', '0011_discussion_book_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='book_id',
        ),
    ]
